package com.landasoft.taoj.pojo;

import java.util.Date;

public class TQuestionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_QUESTION_INFO.ID
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_QUESTION_INFO.NAME
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_QUESTION_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_QUESTION_INFO.CREATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_QUESTION_INFO.UPDATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_QUESTION_INFO.REMARK
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_QUESTION_INFO.ID
     *
     * @return the value of T_QUESTION_INFO.ID
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_QUESTION_INFO.ID
     *
     * @param id the value for T_QUESTION_INFO.ID
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_QUESTION_INFO.NAME
     *
     * @return the value of T_QUESTION_INFO.NAME
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_QUESTION_INFO.NAME
     *
     * @param name the value for T_QUESTION_INFO.NAME
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_QUESTION_INFO.STATE
     *
     * @return the value of T_QUESTION_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_QUESTION_INFO.STATE
     *
     * @param state the value for T_QUESTION_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_QUESTION_INFO.CREATED
     *
     * @return the value of T_QUESTION_INFO.CREATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_QUESTION_INFO.CREATED
     *
     * @param created the value for T_QUESTION_INFO.CREATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_QUESTION_INFO.UPDATED
     *
     * @return the value of T_QUESTION_INFO.UPDATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_QUESTION_INFO.UPDATED
     *
     * @param updated the value for T_QUESTION_INFO.UPDATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_QUESTION_INFO.REMARK
     *
     * @return the value of T_QUESTION_INFO.REMARK
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_QUESTION_INFO.REMARK
     *
     * @param remark the value for T_QUESTION_INFO.REMARK
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}