package com.landasoft.taoj.pojo;

import java.util.Date;

public class TUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.ID
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.USERNAME
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.PASSWD
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.PHONE_NUMBER
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.EMAIL
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.CREATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.UPDATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.REMARK
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.ID
     *
     * @return the value of T_USER_INFO.ID
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.ID
     *
     * @param id the value for T_USER_INFO.ID
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.USERNAME
     *
     * @return the value of T_USER_INFO.USERNAME
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.USERNAME
     *
     * @param username the value for T_USER_INFO.USERNAME
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.PASSWD
     *
     * @return the value of T_USER_INFO.PASSWD
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.PASSWD
     *
     * @param passwd the value for T_USER_INFO.PASSWD
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.PHONE_NUMBER
     *
     * @return the value of T_USER_INFO.PHONE_NUMBER
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.PHONE_NUMBER
     *
     * @param phoneNumber the value for T_USER_INFO.PHONE_NUMBER
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.EMAIL
     *
     * @return the value of T_USER_INFO.EMAIL
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.EMAIL
     *
     * @param email the value for T_USER_INFO.EMAIL
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.STATE
     *
     * @return the value of T_USER_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.STATE
     *
     * @param state the value for T_USER_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.CREATED
     *
     * @return the value of T_USER_INFO.CREATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.CREATED
     *
     * @param created the value for T_USER_INFO.CREATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.UPDATED
     *
     * @return the value of T_USER_INFO.UPDATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.UPDATED
     *
     * @param updated the value for T_USER_INFO.UPDATED
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.REMARK
     *
     * @return the value of T_USER_INFO.REMARK
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.REMARK
     *
     * @param remark the value for T_USER_INFO.REMARK
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}