server:
  port: 8080
  jsp-servlet:
    init-parameters:
      development: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: taojttl
    password: taojttl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  banner:
    charset: UTF-8
  data:
    solr:
      host: http://192.168.25.132:8081/solr/collection2

logging:
  level:
    root: info
  file:
    name: G:\\file\\log\\taoj.log

pagehelper:
  helperDialect: oracle