package com.landasoft.taoj.mapper;

import com.landasoft.taoj.pojo.TQuestionInfo;
import com.landasoft.taoj.pojo.TQuestionInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TQuestionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int countByExample(TQuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int deleteByExample(TQuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int insert(TQuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int insertSelective(TQuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    List<TQuestionInfo> selectByExample(TQuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    TQuestionInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") TQuestionInfo record, @Param("example") TQuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int updateByExample(@Param("record") TQuestionInfo record, @Param("example") TQuestionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int updateByPrimaryKeySelective(TQuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_INFO
     *
     * @mbggenerated Tue Jul 07 09:29:55 CST 2020
     */
    int updateByPrimaryKey(TQuestionInfo record);
}