package com.landasoft.taoj.mapper;

import com.landasoft.taoj.pojo.TQuestionItem;
import com.landasoft.taoj.pojo.TQuestionItemExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TQuestionItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int countByExample(TQuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int deleteByExample(TQuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int insert(TQuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int insertSelective(TQuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    List<TQuestionItem> selectByExample(TQuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    TQuestionItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") TQuestionItem record, @Param("example") TQuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int updateByExample(@Param("record") TQuestionItem record, @Param("example") TQuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int updateByPrimaryKeySelective(TQuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_QUESTION_ITEM
     *
     * @mbggenerated Wed Jul 08 12:00:32 CST 2020
     */
    int updateByPrimaryKey(TQuestionItem record);
}