package com.landasoft.taoj.mapper;

import com.landasoft.taoj.pojo.TUserInfo;
import com.landasoft.taoj.pojo.TUserInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int countByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int deleteByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int insert(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int insertSelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    List<TUserInfo> selectByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    TUserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int updateByExample(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int updateByPrimaryKeySelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Mon Jul 13 15:27:34 CST 2020
     */
    int updateByPrimaryKey(TUserInfo record);
}